# Generated by Django 2.1.1 on 2018-09-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('profile_pic', models.ImageField(null=True, upload_to='images/')),
                ('resume', models.FileField(null=True, upload_to='resume/')),
            ],
        ),
    ]
